base_url = "http://127.0.0.1:1111"
title = "fafa_blog"
description = "Mon blog personnel"
default_language = "fr"
author = "fafa"
theme = "kita"

# Taxonomies
[[taxonomies]]
name = "categories"
feed = true
paginate_by = 5

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 5

[extra.profile]
name = "fafa"
bio = "Développeur fullstack (plus front par le travail), je code une app mobile avec les frameworks Tauri/Leptos, pour sports de combat. Le but principal de ce blog est de partager mon apprentissage de Rust et son écosystème. Je partagerai aussi quelques notes prises lors de mes journées de travail. Par la création de ce blog, j'espère m'engager à commencer et surtout finir ce projet car des side projects, on en a plein mais pas un seul de fini... 🦀 🥊 💻"

[[extra.menu]]
name = "Rust"
url = "$BASE_URL/rust"

[[extra.menu]]
name = "Dev"
url = "$BASE_URL/dev"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"


[extra.footer]
since = 2024
