base_url = "https://fafa-blog.pages.dev/"
title = "fafa_blog"
description = "Mon blog personnel"
default_language = "fr"
author = "fafa"
theme = "kita"
generate_feeds = true
feed_filenames = ["atom.xml"]

[[taxonomies]]
name = "categories"
feed = true
paginate_by = 5

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 5

[[languages.en.taxonomies]]
name = "categories"
feed = true
paginate_by = 5

[[languages.en.taxonomies]]
name = "tags"
feed = true
paginate_by = 5

generate_sitemap = true
generate_robots_txt = true

[extra]
mermaid = true
comment = false

[extra.profile]
name = "fafa"
bio = "Fullstack developer (more focused on frontend through work), I'm building a mobile app with Tauri/Leptos frameworks for combat sports. The main purpose of this blog is to share my learning journey with Rust and its ecosystem. I'll also share some notes taken during my workdays. By creating this blog, I hope to commit myself to starting, and especially finishing this project because we all have plenty of side projects but none of them finished... 🦀 🥊 💻"


[[extra.profile.social]]
name = "github"
url = "https://github.com/fafa-a"

[[extra.profile.social]]
name = "twitter"
url = "https://x.com/FabienPuech"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/fabien-puech/"


[[extra.profile.social]]
name = "rss"
url = "/atom.xml"

[[extra.menu]]
id = "rust"
url = "/rust"

[[extra.menu]]
id = "dev"
url = "/dev"

[[extra.menu]]
id = "tags"
url = "/tags"

[[extra.menu]]
id = "about"
url = "/about"

# Configuration anglaise
[languages.en]
title = "fafa_blog"
description = "My personal blog"

[languages.en.translations]
about = "About"
rust = "Rust"
dev = "Dev"
tags = "Tags"

# Traductions françaises (langue par défaut)
[translations]
about = "About"
rust = "Rust"
dev = "Dev"
tags = "Tags"

[extra.style]
# The custom background color.
# bg_color = ""

# The custom background color in dark mode.
# bg_dark_color = ""

# Enable header blur.
# header_blur = true

# The custom header color, only available when `header_blur` is false.
# header_color = ""

# The custom header color in dark mode, only available when `header_blur` is false.
# header_dark_color = ""

name = "fafa"
[extra.footer]
since = 2024
